scheme --script test-lisp.scm interpreter-base.scm
scheme --script test-meta-lisp.scm interpreter-base.scm
scheme --script test-lisp.scm interpreter.scm
scheme --script test-meta-lisp.scm interpreter.scm
scheme --script test-lisp.scm interpreter-nameless.scm
scheme --script test-meta-lisp.scm interpreter-nameless.scm
scheme --script test-lisp.scm interpreter-meaning.scm
scheme --script test-meta-lisp.scm interpreter-meaning.scm
scheme --script test-lisp.scm interpreter-register.scm
scheme --script test-meta-lisp.scm interpreter-register.scm
scheme --script test-lisp.scm interpreter-bytecode.scm
scheme --script test-meta-lisp.scm interpreter-bytecode.scm